name: build

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0/15 * * * *" # “At every 15th minute from 0 through 59.”  https://crontab.guru/#0/15_*_*_*_*
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      service-name-1:
        image: tindy2013/subconverter
        ports:
           - 25500:25500
    steps:
      - name: get clash config
        curl -o clash.yaml http://127.0.0.1:25500/sub?target=clash&url=https%3A%2F%2Fraw.iqiq.io%2Ffreefq%2Ffree%2Fmaster%2Fv2

      - name: get proxies 
        run: |
          echo "proxies:" > proxies.yaml
          grep -E " - \{" clash.yaml >> proxies.yaml

      - uses: petronny/git-config-user@master
        with:
          path: .
      
      - name: push
        run: |
          set -x
          git add clash.yaml proxies.yaml
          git commit -m "[$(LANG=C date)] auto update" || exit 0
          [ -n "${{ secrets.READ_ONLY }}" ] && git show && exit 0
          git push origin main