name: build

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0/15 * * * *" # “At every 15th minute from 0 through 59.”  https://crontab.guru/#0/15_*_*_*_*
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      sub:
        image: tindy2013/subconverter
        ports:
           - 80:25500
    steps:
      - name: get clash config
        run: |
          curl -k http://localhost:80/version
          curl -k 'http://localhost:80/sub?target=clash&url=https%3A%2F%2Fraw.githubusercontent.com%2Ffreefq%2Ffree%2Fmaster%2Fv2' -o clash.yaml 
          
      - name: get proxies 
        run: |
          echo "proxies:" > proxies.yaml
          grep -E " - \{" clash.yaml >> proxies.yaml

      - uses: petronny/git-config-user@master
        with:
          path: .
      
      - name: push
        run: |
          set -x
          git add clash.yaml proxies.yaml
          git commit -m "[$(LANG=C date)] auto update" || exit 0
          [ -n "${{ secrets.READ_ONLY }}" ] && git show && exit 0
          git push origin main
